resolver: lts-8.8
packages:
- '.'
- location:
    git: https://github.com/dbp/larceny.git
    commit: 70d201e996f56f5cfcd99656e32959c226dd7996
  extra-dep: true
- location:
    git: https://github.com/positiondev/fn.git
    commit: 28d81b33b9513a8f1290b12b161ea1aa6dd6cf4c
  extra-dep: true
  subdirs:
  - fn
extra-deps:
- html-entities-1.1.4
- digestive-functors-0.8.2.0
- heroku-0.1.2.3
- wai-middleware-rollbar-0.4.0
